mybatis:
  type-aliases-package: com.eutopia.entity

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/haruna?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver