mybatis:
  type-aliases-package: com.eutopia.entity

spring:
  datasource:
    url: jdbc:mysql://192.168.1.96:3306/dev_sock?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver