mybatis:
  type-aliases-package: com.eutopia.entity
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

spring:
  datasource:
    url: jdbc:mysql://192.168.1.96:3306/dev_sock?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
    #url: jdbc:mysql://127.0.0.1:3306/shimakaze?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true&useAffectedRows=true
    username: root
    #password: 1234
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
      name: shimakaze

server:
  port: 8763


